### ISSUE TITLE
Texture Offset is limited to range (-100, -100) to (100, 100)

### ISSUE THREAD

**Issue by Drakmyth** [ElectronicBlueberry/Texture-Fonts#1]
**Observed Behavior:**
I loaded in a 256x256 texture where my font characters are all positioned in the right half of the image. Attempting to set the Texture Offset on either axis higher than 100 clamps the value at 100. Playing with the control reveals the lower limit for both axes is -100 (though I can't think of a scenario where less than 0 would be desirable).

**Expected Behavior:**
Texture Offset has a valid range of (0, 0) to (texture_width, texture_height), or a max limit high enough to be effectively unbounded.

**Comment by ElectronicBlueberry** [comment]
Hey.
Firstly, thanks for the bug report!

The min/max values are indeed an oversight. Looking through the code, I now see several places where they might be a hindrance for some use-cases.

As a temporary work-around, you could wrap your texture into an atlas texture and constrain it to the region containing your font.

**Comment by Drakmyth** [comment]
Yeah, my workaround for now was to just reorganize my texture to put the font characters in the upper-left corner, but I wanted to file this since it seemed the limit wasn't intentional.

Awesome job with this addon by the way! It's exactly how I would expect spritefonts to work and the editor is so easy to use!

**Comment by ElectronicBlueberry** [comment]
Should be fixed in 1.1.0

Thanks again for the bug report 👍
